spring:
  application:
    name: vault

  datasource:
    url: jdbc:postgresql://localhost:5433/dnd_game_db
    username: postgres
    password: supersecret
  jpa:
    hibernate:
      ddl-auto: update # Automatically creates your tables for you!
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
server:
  port: 5001 # Crucial: The Vault runs on 8081 so it doesn't clash with your other services