spring.application.name=refree

server.port=8082

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.timeout=2000ms

services.vault.url=${VAULT_URL:http://localhost:8083}
services.bouncer.url=${BOUNCER_URL:http://localhost:8080}

redis.match-state-ttl-seconds=3600
redis.lock-ttl-seconds=10

logging.level.com.dnd=DEBUG