spring:
  application:
    name: referee

server:
  port: 5002

# Custom property for Feign Client to talk to The Vault
vault:
  url: http://localhost:5001

scribe:
  url: http://localhost:5003

# Logging configuration (Optional, but helpful for debugging math)
logging:
  level:
    com.om.referee: DEBUG
    org.springframework.web: INFO
