spring.application.name=lobbyManager

server.port=8081

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

services.vault.url=${VAULT_URL:http://localhost:8083}
services.bouncer.url=${BOUNCER_URL:http://localhost:8080}

lobby.room-ttl-minutes=30
lobby.max-players-per-room=4

logging.level.com.dnd=DEBUG