spring.application.name=lobbyManager
server.port=${PORT:8081}

spring.data.redis.url=${SPRING_DATA_REDIS_URL:redis://localhost:6379}

spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.max-idle=8
spring.data.redis.lettuce.pool.min-idle=0

services.vault.url=${SERVICES_VAULT_URL:http://localhost:8083}
services.bouncer.url=${SERVICES_BOUNCER_URL:http://localhost:8080}

lobby.room-ttl-minutes=30
lobby.max-players-per-room=4

logging.level.com.dnd=INFO
logging.level.org.springframework.web=WARN
