spring.application.name=refree
server.port=${PORT:8082}

spring.data.redis.url=${SPRING_DATA_REDIS_URL:redis://localhost:6379}
spring.data.redis.timeout=2000ms

spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.max-idle=8
spring.data.redis.lettuce.pool.min-idle=0
spring.data.redis.ssl.enabled=true

services.vault.url=${SERVICES_VAULT_URL:http://localhost:8083}
services.bouncer.url=${SERVICES_BOUNCER_URL:http://localhost:8080}
services.scribe.url=${SERVICES_SCRIBE_URL:http://localhost:8084}

redis.match-state-ttl-seconds=3600
redis.lock-ttl-seconds=10

logging.level.com.dungeonsNdragon=INFO
logging.level.org.springframework.web=WARN
